apiVersion: v1
kind: Service
metadata:
  name: db-statefulset
  namespace: myapp-namespace
spec:
  selector:
    app: db-statefulset
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: myapp-namespace
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "kii"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: myapp-namespace
type: Opaque
data:
  POSTGRES_PASSWORD: YW5hc3Rhc2lqYQ==

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  namespace: myapp-namespace
spec:
  serviceName: db-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: db-statefulset
  template:
    metadata:
      labels:
        app: db-statefulset
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
